### ISSUE TITLE
Is there a way to see the current task status on Ansible

### ISSUE THREAD

**Issue by vrathore18** [bendbennett/aws#1]
Now when I run the playbook I see below message on my console.

PLAY [provision stack] *********************************************************

TASK [XXXXX] **********************************************
changed: [localhost]

TASK [] **************************************************
But I can't see the current status like resource and event which is getting created on the AWS side. just the success msg with all the stack out after task completed.

Is there a way by which I can get the cloudformation updates on ansible console during the task. It feels like the task got frozen sometimes. Thanks for the helping me.

**Comment by bendbennett** [comment]
Hi @vrathore18 
You can view the status of the cloud formation stacks that are being provisioned via the [AWS console](https://eu-west-1.console.aws.amazon.com/cloudformation). Alternatively, you could use [terraform](https://github.com/bendbennett/aws-terraform) which will display the status of the resources in the console as they're being provisioned. In terms of having ansible display updates in the console you'll need to dig into the ansible docs.
